### PR TITLE
Add sidecar for image rendering

### PR DESCRIPTION
**Pull request by rajatvig**
Creates a sidecar modeled after - https://grafana.com/docs/grafana/latest/administration/image_rendering/#remote-rendering-service

### CODE REVIEW

**Comment by brancz** [comment]
Could we make this an optional patch? I can imagine not everyone might want this.

**Comment by rajatvig** [comment]
@brancz Have updated the PR to only enable the container when explicitly enabled.

**Comment by rajatvig** [comment]
@brancz Does this look good to merge?

**Comment by brancz** [comment]
I thought about this a bit and I would prefer if this was even more separated to the point where you literally do 

```jsonnet
(import 'kubernetes-grafana/grafana.libsonnet') {
  // setup kubernetes-grafana
} + (import 'kubernetes-grafana/grafana-image-render-sidecar.libsonnet')
```

Then we could even have it in a different repo and just link it from this repo, because to be honest I don't want to maintain this over time, but I'd love to list it as an extension in the documentation.

**Comment by rajatvig** [comment]
@brancz Nice idea. So I moved the image renderer bits to examples and changed the primary grafana.libsonnet to allow extensions for changing the environment, port and add containers.

**Comment by brancz** [comment]
thanks!

**Pull request merged**
