### PR TITLE
Support provider disableDeletion and allowUiUpdates option

### PR DESCRIPTION
**Pull request by yeya24**
Ref: https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards

### CODE REVIEW

**Review by paulfantom — APPROVED** [review]
lgtm

**Comment by yeya24** [comment]
Is this good to go? @paulfantom @brancz To support this in kube-prometheus then I have to update that repo as well?

**Comment by paulfantom** [comment]
> Is this good to go?

For me - yes, but I don't have write permissions ;)

> To support this in kube-prometheus then I have to update that repo as well?

No, kube-prometheus auto-update runs every Monday and will do it for you.

**Comment by brancz** [comment]
I don't really understand this. This repo is all about provisioning a Grafana instance fully immutable from files, this appears to steer against that philosophy. What am I missing?

**Comment by yeya24** [comment]
Yeah, I understand your point. I plan to extract the Grafana part from kube-prometheus stack and use helm chart for Grafana only now.

**Pull request closed without merging**
