### PR TITLE
grafana: do not encode configs and use stringData type

### PR DESCRIPTION
**Pull request by paulfantom**
As in title.

cc @brancz

### CODE REVIEW

**Comment by pharaujo** [comment]
This would be helpful - I'm generating helm chart templates from the output of jsonnet, and also had to do this change because I needed to template the `root_url` in the config.

**Comment by paulfantom** [comment]
ping @brancz

**Review by brancz — APPROVED** [review]

**Comment by justabaka** [comment]
Hello, please take a look at https://github.com/prometheus-operator/kube-prometheus/issues/1356 which has been caused by these changes. Apparently this is not the way stringData works :(

**Comment by pharaujo** [comment]
@justabaka you're correct, [std.encodeUTF8](https://jsonnet.org/ref/stdlib.html#encodeUTF8) returns an array and the secret expects a string. I created https://github.com/brancz/kubernetes-grafana/pull/120 to fix it.

**Pull request merged**
